Output add_category_feed.gif

Set TypingSpeed 50ms
Set FontFamily "Cartograph CF"
Set FontSize 17
Set Width 1280
Set Height 720
Set Theme "Catppuccin Macchiato"

Type "goread"
Enter
Sleep 1s

Type "n"
Sleep 2s
Down
Down

Type "News"
Down
Type "News from around the world!"
Sleep 2s
Enter
Sleep 1s

Down
Down
Enter
Sleep 2s

Type "n"
Type "BBC Europe"
Down
Type "http://feeds.bbci.co.uk/news/world/europe/rss.xml"
Enter
Sleep 2s

Enter
Sleep 1s
Enter
Sleep 5s
