Output colorscheme_import.gif

Set TypingSpeed 50ms
Set FontFamily "Cartograph CF"
Set FontSize 17
Set Width 1280
Set Height 720
Set Theme "Catppuccin Macchiato"

Type "goread --test_colors"
Enter
Sleep 3s

Type "wal --saturate 0.7 -stni ~/pictures/wallpapers/Mountains\ Light.png > /dev/null"
Enter
Sleep 3s

Type "goread --get_colors ~/.cache/wal/colors.json"
Enter
Sleep 3s

Type "goread"
Enter
Sleep 3s
